name: Playwright Component Tests

on:
  workflow_call:
    inputs:
      event-name:
        required: true
        type: string
      ref-name:
        required: true
        type: string

jobs:
  run-component-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Get Playwright version
        id: get-pw-version
        run: echo "version=$(npx playwright --version | awk '{print $2}')" >> "$GITHUB_OUTPUT"

      - name: Restore Playwright browsers from cache
        id: pw-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ steps.get-pw-version.outputs.version }}
          restore-keys: |
            playwright-browsers-${{ steps.get-pw-version.outputs.version }}
            playwright-browsers-

      - name: Determine if cache really missed
        id: check-cache-hit
        run: |
          if [[ "${{ steps.pw-cache.outputs.cache-hit }}" != "true" && "${{ steps.pw-cache.outputs.restore-keys }}" == "" ]]; then
            echo "miss=true" >> $GITHUB_OUTPUT
          else
            echo "miss=false" >> $GITHUB_OUTPUT
          fi

      - name: Install Playwright browsers if cache missed
        if: ${{ steps.check-cache-hit.outputs.miss == 'true' }}
        run: npx playwright install --with-deps chrome

      # Run all tests
      - name: Run all tests
        run: npm run pw:ct
