on:
  workflow_call:
    inputs:
      run-tag:
        required: true
        type: string

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup project dependencies
        run: npm ci

      - name: Get Playwright version
        id: playwright-version
        run: |
          echo "PLAYWRIGHT_VERSION=$(jq -r '.devDependencies.playwright // .dependencies.playwright' package.json)" >> $GITHUB_ENV

      - name: Restore or cache Playwright browsers
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/ms-playwright
          key: playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}
          restore-keys: playwright-browsers-

      - name: Install Playwright browsers if cache missed
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        env:
          PLAYWRIGHT_BROWSERS_PATH: ${{ runner.temp }}/ms-playwright
        run: npx playwright install --with-deps

      - name: Run component tests matching input tag
        run: npm run pw:ct -- --grep ${{ inputs.run-tag }}
