name: Main versioning

on:
  push:
    branches: [main]

jobs:
  versioning:
    environment: main
    runs-on: ubuntu-latest
    name: Main versioning
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - run: npm ci
      - run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
