name: Playwright Component Tests

on:
  workflow_call:
    inputs:
      event-name:
        required: true
        type: string
      ref-name:
        required: true
        type: string
      playwright-version:
        required: true
        type: string

jobs:
  run-component-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Restore browsers from cache
        id: pw-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: |
            playwright-browsers-${{ inputs.playwright-version }}
            playwright-browsers-

      - name: Check if cache missed
        id: check-cache-hit
        run: |
          if [[ "${{ steps.pw-cache.outputs.cache-hit }}" != "true" && "${{ steps.pw-cache.outputs.restore-keys }}" == "" ]]; then
            echo "miss=true" >> $GITHUB_OUTPUT
          else
            echo "miss=false" >> $GITHUB_OUTPUT
          fi

      - name: Download browsers artifact if needed
        if: ${{ steps.check-cache-hit.outputs.miss == 'true' }}
        uses: actions/download-artifact@v4
        with:
          name: playwright-browsers
          path: ~/.cache/ms-playwright

      # Run all tests
      - name: Run all tests
        run: npm run pw:ct
