name: Main workflow start point
on:
  workflow_call:
    inputs:
      event-name:
        required: true
        type: string
      ref-name:
        required: false
        type: string

jobs:
  setup:
    uses: ./.github/workflows/action-project-setup.yaml

  # code-quality:
  #   needs: setup
  #   uses: ./.github/workflows/action-code-quality.yaml

  component-tests:
    needs: setup
    uses: ./.github/workflows/action-run-component-tests.yaml
    with:
      event-name: ${{ inputs.event-name }}
      ref-name: ${{ inputs.ref-name }}
