name: Run Component Tests

on:
  workflow_call:
    inputs:
      event-name:
        required: true
        type: string
      review-state:
        required: false
        type: string
    secrets: {}

jobs:
  run-component-tests:
    runs-on: ubuntu-latest
    needs: [setup] # comes from CI Orchestrator
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        if: ${{ needs.setup.outputs.playwright-browsers-path != '' }}
        run: |
          echo "Using Playwright installed at ${{ needs.setup.outputs.playwright-browsers-path }}"
          echo "PLAYWRIGHT_BROWSERS_PATH=${{ needs.setup.outputs.playwright-browsers-path }}" >> $GITHUB_ENV

      - name: Run component tests
        run: |
          # Default is only-changed
          CMD="npm run test:component -- --only-changed"

          # If this is a PR and it has an approval, run full suite
          if [[ "${{ inputs.event-name }}" == "pull_request" ]] && [[ "${{ inputs.review-state }}" == "approved" ]]; then
            CMD="npm run test:component"
          fi

          echo "Running: $CMD"
          $CMD
