name: Release

on:
  push:
    branches:
      - staging
      - rc
      - main

jobs:
  release-staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - run: npm ci
      - run: npx semantic-release --dry-run
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  release-rc:
    runs-on: ubuntu-latest
    environment: rc
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - run: npm ci
      - run: npx semantic-release --dry-run
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  release-main:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - run: npm ci
      - run: npx semantic-release --dry-run
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
