name: Install Playwright

on:
  workflow_call:
    outputs:
      playwright-path:
        description: 'Playwright path for downstream reference'
        value: ${{ jobs.install-playwright.outputs.pw-path }}
      playwright-version:
        description: 'Current Playwright version'
        value: ${{ jobs.install-playwright.outputs.pw-version }}

jobs:
  install-playwright:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    # Job-level outputs mapped from step outputs
    outputs:
      pw-path: ${{ steps.set-pw-path.outputs.path }}
      pw-version: ${{ steps.get-pw-version.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install project dependencies
        run: npm ci

      - name: Set Playwright browsers path
        id: set-pw-path
        run: |
          path="${RUNNER_TEMP}/ms-playwright"
          echo "path=$path" >> $GITHUB_OUTPUT

      - name: Store Playwright version
        id: get-pw-version
        run: |
          version=$(npx playwright --version | awk '{print $2}')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Restore Playwright browsers from cache
        id: pw-cache
        uses: actions/cache@v4
        with:
          path: '${{ steps.set-pw-path.outputs.path }}'
          key: playwright-browsers-${{ steps.get-pw-version.outputs.version }}
          restore-keys: playwright-browsers-

      - name: Determine if cache really missed
        id: check-cache-hit
        run: |
          if [[ "${{ steps.pw-cache.outputs.cache-hit }}" != "true" && "${{ steps.pw-cache.outputs.restore-keys }}" == "" ]]; then
            echo "miss=true" >> $GITHUB_OUTPUT
          else
            echo "miss=false" >> $GITHUB_OUTPUT
          fi

      - name: Install Playwright browsers if cache missed
        if: ${{ steps.check-cache-hit.outputs.miss == 'true' }}
        run: npx playwright install --with-deps

      # Upload browsers artifact for use by other jobs in the same workflow run
      - name: Upload browsers artifact
        uses: actions/upload-artifact@v4
        with:
          name: playwright-browsers
          path: ${{ steps.set-pw-path.outputs.path }}
