name: Run Component Tests

on:
  workflow_call:
    inputs:
      event-name:
        required: true
        type: string
      review-state:
        required: false
        type: string

jobs:
  run-component-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Run component tests
        run: |
          # Default is only-changed
          CMD="npm run pw:ct -- --only-changed=$GITHUB_BASE_REF"

          # If this is a PR and it has an approval, run full suite
          if [[ "${{ inputs.event-name }}" == "pull_request" ]] && [[ "${{ inputs.review-state }}" == "approved" ]]; then
            CMD="npm run test:component"
          fi

          echo "Running: $CMD"
          $CMD
