name: Playwright Component Tests

on:
  workflow_call:
    inputs:
      event-name:
        required: true
        type: string
      ref-name:
        required: false
        type: string # e.g., github.ref
      playwright-version:
        required: true
        type: string

jobs:
  run-component-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Set Playwright browsers path
        run:
          echo "PLAYWRIGHT_BROWSERS_PATH=${RUNNER_TEMP}/ms-playwright" >> $GITHUB_ENV

          # Restore browsers from cache (fast path)
      - name: Restore browsers from cache
        id: pw-cache
        uses: actions/cache@v4
        with:
          path: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}
          key: playwright-browsers-${{ inputs.playwright-version }}

      # Download artifact if cache missed (ensures browsers are available)
      - name: Download browsers artifact if cache missed
        if: steps.pw-cache.outputs.cache-hit != 'true'
        uses: actions/download-artifact@v4
        with:
          name: playwright-browsers
          path: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}

      - name: Run changed only
        if: ${{ inputs.event-name != 'push' || !startsWith(inputs.ref-name, 'refs/heads/main') }}
        run: npm run pw:ct -- --only-changed=origin/$GITHUB_BASE_REF

      - name: Run all tests
        if: ${{ inputs.event-name == 'push' && startsWith(inputs.ref-name, 'refs/heads/main') }}
        run: npm run pw:ct
