name: Run Component Tests

on:
  workflow_call:
    inputs:
      event-name:
        required: true
        type: string
      ref-name:
        required: false
        type: string # e.g., github.ref

jobs:
  run-component-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:

      - name: Install dependencies
        run: npm ci

      - name: Run changed only
        if: ${{ inputs.event-name != 'push' || !startsWith(inputs.ref-name, 'refs/heads/main') }}
        run: npm run pw:ct -- --only-changed=origin/$GITHUB_BASE_REF

      - name: Run all tests
        if: ${{ inputs.event-name == 'push' && startsWith(inputs.ref-name, 'refs/heads/main') }}
        run: npm run pw:ct
