name: Release

on:
  pull_request:
    branches:
      - dev
  #     - staging
  #     - rc
  #     - main
  #   types: [closed]
  push:
    branches:
      - dev
      - ryne/feature/sc-190/version-labeling-1

jobs:
  release:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed for tags & full history

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release --dry-run
