name: Main workflow start point
on:
  workflow_call:
    inputs:
      event-name:
        required: true
        type: string
      ref-name:
        required: false
        type: string

jobs:
  formatter:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v5

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
        node-version: 'lts/*'

    - name: Setup project dependencies
      run: npm ci

    - name: Run Prettier
      run: npx prettier --check "src/**/*.{ts,tsx,js,jsx,json,css,md}"

  linter:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
        node-version: 'lts/*'

    - name: Setup project dependencies
      run: npm ci

    - name: Run ESLint
      run: npx eslint "src/**/*.{ts,tsx,js,jsx}" --max-warnings=0

  typecheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
        node-version: 'lts/*'

    - name: Setup project dependencies
      run: npm ci

    - name: Run TypeScript typecheck
      run: npm run typecheck

  playwright:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
        node-version: 'lts/*'

    - name: Setup project dependencies
      run: npm ci

    - name: Get Playwright version
      id: get-pw-version
      run: echo "version=$(npx playwright --version | awk '{print $2}')" >> $GITHUB_OUTPUT

    - name: Cache Playwright browsers
      id: pw-cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-browsers-${{ steps.get-pw-version.outputs.version }}
        restore-keys: playwright-browsers-

    - name: Install Playwright browsers if cache missed
      if: ${{ steps.pw-cache.outputs.cache-hit != 'true' }}
      run: npx playwright install --with-deps --only-shell chromium

    - name: Run @sanity tests for changed files
      if: ${{ inputs.event-name == 'pull_request' }}
      run: npm run pw:ct -- --grep @sanity --only-changed=origin/$GITHUB_BASE_REF

    - name: Run @a11y, @interaction, @visual tests for changed files
      if: ${{ inputs.event-name == 'push' && startsWith(inputs.ref-name, 'refs/heads/main') }}
      run: npm run pw:ct -- --grepInvert @sanity --only-changed=origin/$GITHUB_BASE_REF

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        if-no-files-found: 'ignore'
        name: playwright-report
        path: playwright-report/
        retention-days: 10
