name: Project Environment Setup

on:
  workflow_call:
    inputs:
      install-playwright:
        required: true
        type: boolean

    outputs:
      playwright-browsers-path:
        description: 'Path where Playwright browsers are installed'
        value: ${{ jobs.install-playwright.outputs.playwright-browsers-path || '' }}
      playwright-version:
        description: 'Playwright version installed'
        value: ${{ jobs.install-playwright.outputs.playwright-version || '' }}

jobs:
  project-setup:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    outputs:
      node-cache-key: ${{ steps.node-cache-key.outputs.key || '' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js and restore npm cache
        id: node-cache-key
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install project dependencies
        run: npm ci

  install-playwright:
    if: ${{ inputs.install-playwright }}
    needs: project-setup
    uses: ./.github/workflows/action-install-playwright.yaml
