name: Install Playwright

on:
  workflow_call:

jobs:
  install-playwright:
    runs-on: ubuntu-latest
    env:
      CACHE_MISS: ${{ steps.pw-cache.outputs.cache-hit != 'true' && steps.pw-cache.outputs.restore-keys == '' }}

    defaults:
      run:
        shell: bash

    outputs:
      playwright-version: ${{ steps.get-pw-version.outputs.version }}
      playwright-path: ${{ steps.set-pw-path.outputs.path }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install project dependencies
        run: npm ci

      - name: Store Playwright version
        id: get-pw-version
        run: |
          version=$(npx playwright --version | awk '{print $2}')
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "PLAYWRIGHT_VERSION=$version" >> $GITHUB_ENV

      - name: Set Playwright browsers path env
        id: set-pw-path
        run: |
          path="${RUNNER_TEMP}/ms-playwright"
          echo "PLAYWRIGHT_BROWSERS_PATH=$path" >> $GITHUB_ENV
          echo "path=$path" >> $GITHUB_OUTPUT

      - name: Restore Playwright browsers from cache if able
        id: pw-cache
        uses: actions/cache@v4
        with:
          path: '${{ env.PLAYWRIGHT_BROWSERS_PATH }}'
          key: playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}
          restore-keys: playwright-browsers-

      - name: Install Playwright browsers if cache missed
        if: ${{ env.CACHE_MISS }}
        run: npx playwright install --with-deps

      - name: Upload browsers artifact if install ran
        if: ${{ env.CACHE_MISS }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-browsers
          path: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}
