name: Code Quality Checks

on:
  workflow_call:

jobs:
  check-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run lint-staged (ESLint + Prettier)
        run: npx lint-staged

      - name: Run TypeScript typecheck
        run: npm run typecheck
