name: Component Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sanity-tests:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/common-setup.yaml
    with:
      run-tag: '@sanity'

  a11y-tests:
    if: github.event_name == 'push'
    uses: ./.github/workflows/common-setup.yaml
    with:
      run-tag: '@a11y'

  visual-tests:
    if: github.event_name == 'push'
    uses: ./.github/workflows/common-setup.yaml
    with:
      run-tag: '@visual'

  interaction-tests:
    if: github.event_name == 'push'
    uses: ./.github/workflows/common-setup.yaml
    with:
      run-tag: '@interaction'
