name: Run component tests

concurrency:
  group: component-tests-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [main]
  pull_request_review:
    types: [submitted] # Trigger when a review is submitted
  workflow_dispatch:

jobs:
  setup:
    uses: ./.github/workflows/project-setup.yaml

  type-check:
    if: github.event_name == 'pull_request'
    needs: setup
    uses: ./.github/workflows/typecheck.yaml

  sanity-tests:
    if: github.event_name == 'pull_request'
    needs: setup
    uses: ./.github/workflows/component-test-runner.yaml
    with:
      run-tag: '@sanity'

  a11y-tests:
    if: github.event_name == 'pull_request_review' && github.event.review.state == 'approved'
    needs: setup
    uses: ./.github/workflows/component-test-runner.yaml
    with:
      run-tag: '@a11y'

  visual-tests:
    if: github.event_name == 'pull_request_review' && github.event.review.state == 'approved'
    needs: setup
    uses: ./.github/workflows/component-test-runner.yaml
    with:
      run-tag: '@visual'

  interaction-tests:
    if: github.event_name == 'pull_request_review' && github.event.review.state == 'approved'
    needs: setup
    uses: ./.github/workflows/component-test-runner.yaml
    with:
      run-tag: '@interaction'
