# .github/workflows/ci-orchestrator.yaml
name: CI Orchestrator

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  setup:
    uses: ./.github/workflows/action-project-setup.yaml
    with:
      install-playwright: false # setup itself just handles repo + deps

  code-quality:
    needs: setup
    uses: ./.github/workflows/action-code-quality.yaml

  install-playwright:
    needs: setup
    uses: ./.github/workflows/action-install-playwright.yaml

  component-tests:
    needs: [setup, install-playwright]
    uses: ./.github/workflows/action-run-component-tests.yaml
    with:
      event-name: ${{ github.event_name }}
      review-state: ${{ github.event.review.review_state || '' }}
