name: CI Orchestrator
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  kickoff:
    uses: ./.github/workflows/action-start-main-workflow.yaml
    with:
      base-ref-name: ${{ github.base_ref }}
      event-name: ${{ github.event_name }}
      ref-name: ${{ github.ref }}
