name: Component test runner

on:
  workflow_call:
    inputs:
      run-tag:
        required: true
        type: string

jobs:
  run-tests:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run tests
        run: npm run pw:ct -- --grep ${{ inputs.run-tag }}

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.run-tag }}-results
          path: test-results/
          retention-days: 30
