name: Component test runner

on:
  workflow_call:
    inputs:
      run-tag:
        required: true
        type: string

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # - name: Download cached project
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: deps
      #     path: ./

      - name: Install deps
        run: npm ci

      - name: Playwright cache
        env:
          PLAYWRIGHT_BROWSERS_PATH: ~/.cache/ms-playwright
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright browsers if needed
        run: npx playwright install --with-deps

      - name: Run sanity tests
        run: npm run pw:ct -- --grep ${{ inputs.run-tag }}

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.run-tag }}-results
          path: test-results/
          retention-days: 30
