name: Component Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache node_modules
        id: node-cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Cache Playwright browsers
        id: pw-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright browsers
        if: steps.pw-cache.outputs.cache-hit != 'true'
        run: npx playwright install

  sanity:
    name: Sanity Tests (PR)
    if: github.event_name == 'pull_request'
    needs: setup
    runs-on: ubuntu-latest
    uses: actions/checkout@v3
    steps:
      - name: Run Sanity Tests
        run: npm run pw:ct -- --grep @sanity --reporter=dot

  full-suite:
    name: Full Suite Tests (Main)
    if: github.event_name == 'push'
    needs: setup
    runs-on: ubuntu-latest
    uses: actions/checkout@v3
    steps:
      - name: Run Full Suite (excluding sanity)
        run: npm run pw:ct -- --grep-invert @sanity --reporter=dot
