name: Component Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install

  sanity:
    name: Sanity Tests (PR)
    needs: setup
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Run Sanity Tests
        run: npm run pw:ct -- --grep @sanity --reporter=dot

  full-suite:
    name: Full Suite Tests (Main)
    needs: setup
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Run Full Suite (excluding sanity)
        run: npm run pw:ct -- --grep-invert @sanity --reporter=dot
