on:
  workflow_call:
    inputs:
      run-tag:
        required: true
        type: string

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup environment
        run: npm ci

      - name: Check Playwright cache
        id: playwright-cache
        env:
          PLAYWRIGHT_BROWSERS_PATH: ~/.cache/ms-playwright
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright browsers if needed
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        env:
          PLAYWRIGHT_BROWSERS_PATH: ~/.cache/ms-playwright
        run: npx playwright install --with-deps

      - name: Run sanity tests
        run: npm run pw:ct -- --grep ${{ inputs.run-tag }}
