name: Run Tests

on:
  workflow_call:
    inputs:
      run-tag:
        required: true
        type: string

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download deps
        uses: actions/download-artifact@v4
        with:
          name: deps
          path: ./

      - name: Install deps
        run: npm ci

      - name: Restore Playwright cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Run sanity tests
        run: npm run pw:ct -- --grep ${{ inputs.run-tag }} --reporter=dot

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: sanity-test-results
          path: test-results/
          retention-days: 30
