name: Component Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  setup:
    uses: ./.github/workflows/common-setup.yaml
    with:
      run-id: ${{ github.run_id }}

  tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download deps
        uses: actions/download-artifact@v4
        with:
          name: deps
          path: ./

      - name: Install deps
        run: npm ci

      - name: Restore Playwright cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Run sanity tests
        if: github.event_name == 'pull_request'
        run: npm run pw:ct -- --grep @sanity --reporter=dot

      - name: Run full test suite
        if: github.event_name == 'push'
        run: npm run pw:ct -- --grep-invert @sanity --reporter=dot

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: test-results/
          retention-days: 30
