name: Project setup

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      node-modules-cache-hit: ${{ steps.node-cache.outputs.cache-hit }}
      playwright-cache-hit: ${{ steps.playwright-cache.outputs.cache-hit }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Restore Node modules cache
        id: node-cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node-modules-

      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Restore Playwright cache
        id: playwright-cache
        env:
          PLAYWRIGHT_BROWSERS_PATH: ~/.cache/ms-playwright
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        env:
          PLAYWRIGHT_BROWSERS_PATH: ~/.cache/ms-playwright
        run: npx playwright install --with-deps
