name: Run type check

on:
  workflow_call:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run type check
        run: npm run typecheck
